import { Resource } from "../types";

export const sampleData: Resource[] = [
  {
    id: "123",
    createdTime: "2023-02-21T10:09:32.000Z",
    fields: {
      name: "Entry 1 Titel",
      public: true,
      new: true,
      brand: "",
      description:
        "Entry 1 Description",
      tags: ["lokale Angebote", "Konferenz"],
      website: "https://www.entry1.de",
      twitter: "https://twitter.com/entry1",
      instagram: "https://instagram.com/entry1",
      youtube: "http://www.youtube.com/c/entry1",
      twitch: "https://www.twitch.tv/entry1",
      facebook: "",
      newsletter: "",
      tikTok: "",
      podcast: "",
      telegram: "",
      meetup: "",
      linkedin: "",
      discord: "",
      email: "",
      blog: "",
      book: "",
      region: "Deutschland",
      cities: ["Berlin", "Leipzig"],
      language: ["DE"],
      audience: ["kids"],
      "create date": "2021-02-12",
      "update date": "2021-02-12",
    },
  },
  {
    id: "123",
    createdTime: "2023-02-21T10:09:32.000Z",
    fields: {
      name: "Entry 2 Title",
      public: true,
      new: false,
      brand: "",
      description:
        "Entry 2 Description",
      tags: ["Konferenz", "Initiative"],
      website: "https://www.entry2.de",
      twitter: "https://twitter.com/entry2",
      instagram: "https://instagram.com/entry2",
      youtube: "http://www.youtube.com/c/entry2",
      twitch: "https://www.twitch.tv/entry2",
      facebook: "",
      newsletter: "",
      tikTok: "",
      podcast: "",
      telegram: "",
      meetup: "",
      linkedin: "",
      discord: "",
      email: "",
      blog: "",
      book: "",
      region: "Deutschland",
      cities: ["Leipzig"],
      language: ["EN"],
      audience: ["adults"],
      "create date": "2021-02-12",
      "update date": "2021-02-12",
    },
  },
  {
    id: "123",
    createdTime: "2023-02-21T10:09:32.000Z",
    fields: {
      name: "Entry 3 Title",
      public: true,
      new: false,
      brand: "",
      description:
        "Entry 3 Description",
      tags: ["Hackspace", "Netzwerk"],
      website: "https://www.entry3.de",
      twitter: "https://twitter.com/entry3",
      instagram: "https://instagram.com/entry3",
      youtube: "http://www.youtube.com/c/entry3",
      twitch: "https://www.twitch.tv/entry3",
      facebook: "",
      newsletter: "",
      tikTok: "",
      podcast: "",
      telegram: "",
      meetup: "",
      linkedin: "",
      discord: "",
      email: "",
      blog: "",
      book: "",
      region: "Deutschland",
      cities: ["Leipzig"],
      language: ["EN"],
      audience: ["adults"],
      "create date": "2021-02-12",
      "update date": "2021-02-12",
    },
  },
];
